package expression

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
)

// The expression surface Microsoft documents, as opposed to the one this
// emulator implements.
//
// WHY THIS FILE EXISTS, and it is the whole point of the inventory. `Allowlist`
// is maintained from the emulator's side: a member is listed because somebody
// here thought about it. Anything generated from that allowlist is
// self-referential -- it can prove the emulator is consistent with itself and
// can never show a member Microsoft documents that nobody here has heard of.
//
// This file used to be the other side, and it was HAND-TRANSCRIBED, which is the
// same trap one level up: a hand-copied record of somebody else's document
// drifts from it silently. It did. Compared against Microsoft's own sources it
// carried `LastError.Element` and `ElementPath`, which Microsoft does not
// document, while `Path` and `PolicyId`, which it does, were absent, and
// `context.Backend`, `context.Workspace` and `Deployment.SustainabilityInfo`
// were missing outright. The inventory read 113 of 113 against a denominator we
// had written ourselves.
//
// So the surface is now DERIVED. `documented.json` is generated by
// scripts/derive_expression_surface.py from two independent Microsoft sources
// vendored at pinned commits under third_party/microsoft/, and `make
// check-expression-surface` fails when the two disagree. Updating Microsoft's
// documented surface is now re-vendoring a file, not editing a Go literal.
//
// PROVENANCE, stated because it bounds what this proves: both sources are
// DOCUMENTS, not a running APIM instance. A member Azure supports but documents
// nowhere is still invisible here, and the two sources disagree in places --
// `Product.SubscriptionLimit` against `SubscriptionsLimit` -- which is recorded
// per member rather than averaged away.

//go:embed documented.json
var documentedSurface []byte

// DocumentedMember is one member of Microsoft's documented context graph,
// carrying the vendored sources that name it. A member only one source knows
// about is a weaker claim than one both carry, and hiding that would make the
// inventory look more certain than it is.
type DocumentedMember struct {
	Type    string   `json:"type"`
	Name    string   `json:"name"`
	Sources []string `json:"sources"`
	// Declared is the C# type each source gives the member, keyed by source.
	// This is what makes a SHAPE gate possible: a member inventory checks that
	// a name exists, and every type-level defect this package has shipped --
	// `Url.Query` returning text where Microsoft types a dictionary, headers
	// answering one string where Microsoft types an array -- passed that check
	// while returning the wrong thing.
	Declared map[string]string `json:"declared,omitempty"`
}

type documentedFile struct {
	Members        []DocumentedMember `json:"members"`
	FrameworkTypes []string           `json:"frameworkTypes"`
}

func loadDocumented() documentedFile {
	return parseDocumented(documentedSurface)
}

// parseDocumented panics rather than returning an error. The file is embedded at
// build time and generated by a gated script, so an unreadable one is a broken
// BUILD, not a runtime condition, and degrading to an empty surface would make
// the inventory report that Microsoft documents nothing.
func parseDocumented(raw []byte) documentedFile {
	var file documentedFile
	if err := json.Unmarshal(raw, &file); err != nil {
		panic(fmt.Sprintf("documented.json is not readable: %v", err))
	}
	return file
}

// Documented returns the type/member pairs Microsoft documents for the
// `context` object graph.
func Documented() []Member {
	file := loadDocumented()
	members := make([]Member, 0, len(file.Members))
	for _, member := range file.Members {
		members = append(members, Member{Type: member.Type, Name: member.Name})
	}
	return members
}

// DocumentedSources reports which vendored sources name a member, and whether
// it is documented at all.
func DocumentedSources(typ, name string) ([]string, bool) {
	for _, member := range loadDocumented().Members {
		if member.Type == typ && member.Name == name {
			return member.Sources, true
		}
	}
	return nil, false
}

// FrameworkTypes returns the .NET types Microsoft's reference lists as usable
// from a policy expression.
//
// These bound what a `framework` allowlist entry may claim. Microsoft lists
// `X509Certificate2` as available without enumerating its members, so the
// members this emulator answers on `context.Request.Certificate` are OUR reading
// of a .NET type. That is a weaker claim than a documented context member and a
// much stronger one than an extension: the type really is available in a tenant.
func FrameworkTypes() []string {
	types := append([]string(nil), loadDocumented().FrameworkTypes...)
	sort.Strings(types)
	return types
}

// documentedIndex is Documented() keyed for lookup.
func documentedIndex() map[string]map[string]bool {
	index := map[string]map[string]bool{}
	for _, member := range Documented() {
		if index[member.Type] == nil {
			index[member.Type] = map[string]bool{}
		}
		index[member.Type][member.Name] = true
	}
	return index
}

// DocumentedTypes returns the C# type each vendored source declares for a
// member, keyed by source. Empty when neither names one.
//
// The two can disagree -- `IUrl.Port` is `int` in the reference and `string` in
// the toolkit -- so both are returned rather than one being chosen here.
func DocumentedTypes(typ, name string) map[string]string {
	for _, member := range loadDocumented().Members {
		if member.Type == typ && member.Name == name {
			return member.Declared
		}
	}
	return nil
}
